namiestnik:
  - 7588071 # https://www.margonem.pl/profile/view,7588071 - Zireath
radny:
  - 9696571 # https://www.margonem.pl/profile/view,9696571 - Vitalia Chiaraventura
  - 6657578 # https://www.margonem.pl/profile/view,6657578 - Rivian Devisson
narrator:
  - 125880  # https://www.margonem.pl/profile/view,125880  - Materios Dragonius
  - 7508340 # https://www.margonem.pl/profile/view,7508340 - Runar Knut
  - 6621324 # https://www.margonem.pl/profile/view,6621324 - Rothen
  - 5699334 # https://www.margonem.pl/profile/view,5699334 - Anward
  - 7925933 # https://www.margonem.pl/profile/view,7925933 - Mirar Korda
  - 9696571 # https://www.margonem.pl/profile/view,9696571 - Vitalia Chiaraventura
  - 6192857 # https://www.margonem.pl/profile/view,6192857 - Karendar
  - 1535485 # https://www.margonem.pl/profile/view,1535485 - Glieve
  - 9891163 # https://www.margonem.pl/profile/view,9891163 - Moira von Tepes
  - 9655889 # https://www.margonem.pl/profile/view,9655889 - Crissa
special:
  - 5623545 # https://www.margonem.pl/profile/view,5623545 - Kris Aphalon
  - 70699   # https://www.margonem.pl/profile/view,70699   - Ath`Lar Draa`Ilythiiri
  - 30508   # https://www.margonem.pl/profile/view,30508   - Leira Elamshin
  - 2328121 # https://www.margonem.pl/profile/view,2328121 - Shiraya
  - 345207  # https://www.margonem.pl/profile/view,345207  - Minstrella
  - 883090  # https://www.margonem.pl/profile/view,883090  - Noys Hollyhook-Rumore
  - 256795  # https://www.margonem.pl/profile/view,256795  - Mateusz z Rocevaux
  - 5424002 # https://www.margonem.pl/profile/view,5424002 - Korano Ligatur
  - 7588071 # https://www.margonem.pl/profile/view,7588071 - Zireath
  - 5699334 # https://www.margonem.pl/profile/view,5699334 - Anward
